#!/usr/bin/env bash
# Displays "Best School" 10 times, with "Hi" after the 9th
i=0
while [ $i -lt 10 ]; do
    echo "Best School"
    i=$((i + 1))
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
done
